/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "vs-bg": "#1E1E1E",
        "vs-surface": "#252526",
        "vs-elevated": "#2D2D30",
        "vs-border": "#3E3E42",
        "vs-toolbar": "#2C2C2E",
        "vs-text": "#D4D4D4",
        "vs-muted": "#9D9D9D",
        "vs-dim": "#6B6B6B",
        "vs-accent": "#0098FF",
        "vs-accent-dark": "#007ACC",
        "vs-selection": "#264F78",
        "vs-success": "#4EC94E",
        "vs-error": "#F44747",
        "vs-warn": "#CCA700",
        "syn-keyword": "#569CD6",
        "syn-string": "#CE9178",
        "syn-comment": "#6A9955",
        "syn-type": "#4EC9B0",
        "syn-number": "#B5CEA8",
        "syn-register": "#9CDCFE",
        "syn-opcode": "#DCDCAA",
        "syn-directive": "#C586C0",
        "syn-label": "#C8C8C8",
        "tree-package": "#E8C46A",
        "tree-class": "#4EC9B0",
        "tree-method": "#DCDCAA",
        "tree-field": "#9CDCFE",
      },
      fontFamily: {
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "Cascadia Code",
          "Consolas",
          "Monaco",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        "code-sm": ["12px", "1.6"],
        "code-base": ["13px", "1.6"],
      },
    },
  },
  plugins: [],
};
