"""Sphinx configuration for the `platypus` Python API docs.

The docs are generated by `autodoc`, which imports the compiled `platypus`
extension module and reads the docstrings PyO3 carries over from the Rust
source (rust/src/python/*.rs). The module must therefore be importable when
Sphinx runs — see docs/README.md (local) and .readthedocs.yaml (CI).
"""

project = "Project Platypus"
author = "Project Platypus"
copyright = "Project Platypus"

# Keep in sync with rust/Cargo.toml / pyproject if you start pinning versions.
release = "0.1.0"
version = "0.1"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",      # tolerate Google/NumPy-style docstring sections
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "myst_parser",              # render the Markdown scripting guide
]

# Treat both reStructuredText and Markdown sources as documents.
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

autosummary_generate = True
autodoc_member_order = "groupwise"
autodoc_default_options = {
    "members": True,
    "undoc-members": True,       # still list members that lack a docstring
    "show-inheritance": True,
}
# PyO3 methods expose `__text_signature__`; let autodoc use it for signatures.
autodoc_typehints = "description"

napoleon_google_docstring = True
napoleon_numpy_docstring = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Furo if available, otherwise fall back to the always-present default theme so
# a docs build never fails just because the theme isn't installed.
try:
    import furo  # noqa: F401
    html_theme = "furo"
except ImportError:
    html_theme = "alabaster"

html_title = "Project Platypus — Python API"
html_static_path = ["_static"]


def _module_importable() -> bool:
    try:
        import platypus  # noqa: F401
        return True
    except ImportError:
        return False


# Emit a clear, early warning if the extension module isn't built — otherwise
# autodoc fails with a confusing "no module named platypus" deep in the build.
if not _module_importable():
    import warnings
    warnings.warn(
        "The `platypus` extension module is not importable in this environment. "
        "Build it first (see docs/README.md): `pip install ./rust` or "
        "`cd rust && maturin develop --features python`. autodoc pages will be "
        "empty until it is."
    )
